"""TypedDict definitions for Google Vertex AI generateContent API.

Auto-generated from the Vertex AI discovery document (v1beta1).
Do not edit manually — regenerate with:
  python scripts/generate_types.py --version v1beta1

API reference (discovery docs):
  https://aiplatform.googleapis.com/$discovery/rest?version=v1
  https://aiplatform.googleapis.com/$discovery/rest?version=v1beta1
"""

from __future__ import annotations

from typing import Any, Literal, TypedDict  # noqa: UP035

__all__ = [
    "Blob",
    "FileData",
    "FunctionCall",
    "FunctionResponse",
    "FunctionResponsePart",
    "ExecutableCode",
    "CodeExecutionResult",
    "VideoMetadata",
    "Part",
    "Content",
    "FunctionDeclaration",
    "Tool",
    "FunctionCallingConfig",
    "ToolConfig",
    "ThinkingConfig",
    "GenerationConfig",
    "SafetySetting",
    "GenerateContentRequest",
    "Candidate",
    "UsageMetadata",
    "PromptFeedback",
    "GenerateContentResponse",
]


class Blob(TypedDict, total=False):
    """A content blob. A Blob contains data of a specific media type. It is used to represent images,
    audio, and video."""

    # Required
    data: str
    # Optional
    displayName: str
    # Required
    mimeType: str


class FileData(TypedDict, total=False):
    """URI-based data. A FileData message contains a URI pointing to data of a specific media type. It
    is used to represent images, audio, and video stored in Google Cloud Storage."""

    # Optional
    displayName: str
    # Required
    fileUri: str
    # Required
    mimeType: str


class FunctionCall(TypedDict, total=False):
    """A predicted FunctionCall returned from the model that contains a string representing the
    FunctionDeclaration.name and a structured JSON object containing the parameters and their
    values."""

    # Optional
    args: dict[str, Any]
    # Optional
    id: str
    # Optional
    name: str
    # Optional
    partialArgs: list[dict[str, Any]]
    # Optional
    willContinue: bool


class FunctionResponse(TypedDict, total=False):
    """The result output from a FunctionCall that contains a string representing the
    FunctionDeclaration.name and a structured JSON object containing any output from the function is
    used as context to the model. This should contain the result of a `FunctionCall` made based on
    model prediction."""

    # Optional
    id: str
    # Required
    name: str
    # Optional
    parts: list[FunctionResponsePart]
    # Required
    response: dict[str, Any]
    # Optional
    scheduling: Literal["SCHEDULING_UNSPECIFIED", "SILENT", "WHEN_IDLE", "INTERRUPT"]


class FunctionResponsePart(TypedDict, total=False):
    """A datatype containing media that is part of a `FunctionResponse` message. A
    `FunctionResponsePart` consists of data which has an associated datatype. A
    `FunctionResponsePart` can only contain one of the accepted types in
    `FunctionResponsePart.data`. A `FunctionResponsePart` must have a fixed IANA MIME type
    identifying the type and subtype of the media if the `inline_data` field is filled with raw
    bytes."""

    # URI based data
    fileData: dict[str, Any]
    # Inline media bytes
    inlineData: dict[str, Any]


class ExecutableCode(TypedDict, total=False):
    """Code generated by the model that is meant to be executed, and the result returned to the model.
    Generated when using the `CodeExecution` tool, in which the code will be automatically executed,
    and a corresponding CodeExecutionResult will also be generated."""

    # Required
    code: str
    # Required
    language: Literal["LANGUAGE_UNSPECIFIED", "PYTHON"]


class CodeExecutionResult(TypedDict, total=False):
    """Result of executing the ExecutableCode. Generated only when the `CodeExecution` tool is used."""

    # Required
    outcome: Literal[
        "OUTCOME_UNSPECIFIED",
        "OUTCOME_OK",
        "OUTCOME_FAILED",
        "OUTCOME_DEADLINE_EXCEEDED",
    ]
    # Optional
    output: str


class VideoMetadata(TypedDict, total=False):
    """Provides metadata for a video, including the start and end offsets for clipping and the frame
    rate."""

    # Optional
    endOffset: str
    # Optional
    fps: float
    # Optional
    startOffset: str


class Part(TypedDict, total=False):
    """A datatype containing media that is part of a multi-part Content message. A `Part` consists of
    data which has an associated datatype. A `Part` can only contain one of the accepted types in
    `Part.data`. For media types that are not text, `Part` must have a fixed IANA MIME type
    identifying the type and subtype of the media if `inline_data` or `file_data` field is filled
    with raw bytes."""

    # Optional
    codeExecutionResult: CodeExecutionResult
    # Optional
    executableCode: ExecutableCode
    # Optional
    fileData: FileData
    # Optional
    functionCall: FunctionCall
    # Optional
    functionResponse: FunctionResponse
    # Optional
    inlineData: Blob
    # per part media resolution
    mediaResolution: dict[str, Any]
    # Optional
    text: str
    # Optional
    thought: bool
    # Optional
    thoughtSignature: str
    # Optional
    videoMetadata: VideoMetadata


class Content(TypedDict, total=False):
    """The structured data content of a message. A Content message contains a `role` field, which
    indicates the producer of the content, and a `parts` field, which contains the multi-part data
    of the message."""

    # Required
    parts: list[Part]
    # Optional
    role: str


class FunctionDeclaration(TypedDict, total=False):
    """Structured representation of a function declaration as defined by the [OpenAPI 3.0
    specification](https://spec.openapis.org/oas/v3.0.3). Included in this declaration are the
    function name, description, parameters and response type. This FunctionDeclaration is a
    representation of a block of code that can be used as a `Tool` by the model and executed by the
    client."""

    # Optional
    description: str
    # Required
    name: str
    # Optional
    parameters: dict[str, Any]
    # Optional
    parametersJsonSchema: Any
    # Optional
    response: dict[str, Any]
    # Optional
    responseJsonSchema: Any


class Tool(TypedDict, total=False):
    """Tool details that the model may use to generate response. A `Tool` is a piece of code that
    enables the system to interact with external systems to perform an action, or set of actions,
    outside of knowledge and scope of the model. A Tool object should contain exactly one type of
    Tool (e.g FunctionDeclaration, Retrieval or GoogleSearchRetrieval)."""

    # Optional
    codeExecution: dict[str, Any]
    # Optional
    computerUse: dict[str, Any]
    # Optional
    enterpriseWebSearch: dict[str, Any]
    # Optional
    functionDeclarations: list[FunctionDeclaration]
    # Optional
    googleMaps: dict[str, Any]
    # Optional
    googleSearch: dict[str, Any]
    # Optional
    googleSearchRetrieval: dict[str, Any]
    # Optional
    parallelAiSearch: dict[str, Any]
    # Optional
    retrieval: dict[str, Any]
    # Optional
    urlContext: dict[str, Any]


class FunctionCallingConfig(TypedDict, total=False):
    """Function calling config."""

    # Optional
    allowedFunctionNames: list[str]
    # Optional
    mode: Literal["MODE_UNSPECIFIED", "AUTO", "ANY", "NONE", "VALIDATED"]
    # Optional
    streamFunctionCallArguments: bool


class ToolConfig(TypedDict, total=False):
    """Tool config. This config is shared for all tools provided in the request."""

    # Optional
    functionCallingConfig: FunctionCallingConfig
    # Optional
    retrievalConfig: dict[str, Any]


class ThinkingConfig(TypedDict, total=False):
    """Configuration for the model's thinking features. "Thinking" is a process where the model breaks
    down a complex task into smaller, manageable steps. This allows the model to reason about the
    task, plan its approach, and execute the plan to generate a high-quality response."""

    # Optional
    includeThoughts: bool
    # Optional
    thinkingBudget: int
    # Optional
    thinkingLevel: Literal["THINKING_LEVEL_UNSPECIFIED", "LOW", "MEDIUM", "HIGH", "MINIMAL"]


class GenerationConfig(TypedDict, total=False):
    """Configuration for content generation. This message contains all the parameters that control how
    the model generates content. It allows you to influence the randomness, length, and structure of
    the output."""

    # Optional
    audioTimestamp: bool
    # Optional
    candidateCount: int
    # Optional
    enableAffectiveDialog: bool
    # Optional
    frequencyPenalty: float
    # Optional
    imageConfig: dict[str, Any]
    # Optional
    logprobs: int
    # Optional
    maxOutputTokens: int
    # Optional
    mediaResolution: Literal[
        "MEDIA_RESOLUTION_UNSPECIFIED",
        "MEDIA_RESOLUTION_LOW",
        "MEDIA_RESOLUTION_MEDIUM",
        "MEDIA_RESOLUTION_HIGH",
    ]
    # Optional
    modelConfig: dict[str, Any]
    # Optional
    presencePenalty: float
    # Optional
    responseJsonSchema: Any
    # Optional
    responseLogprobs: bool
    # Optional
    responseMimeType: str
    # Optional
    responseModalities: list[Literal["MODALITY_UNSPECIFIED", "TEXT", "IMAGE", "AUDIO"]]
    # Optional
    responseSchema: dict[str, Any]
    # Optional
    routingConfig: dict[str, Any]
    # Optional
    seed: int
    # Optional
    speechConfig: dict[str, Any]
    # Optional
    stopSequences: list[str]
    # Optional
    temperature: float
    # Optional
    thinkingConfig: ThinkingConfig
    # Optional
    topK: float
    # Optional
    topP: float


class SafetySetting(TypedDict, total=False):
    """A safety setting that affects the safety-blocking behavior. A SafetySetting consists of a harm
    category and a threshold for that category."""

    # Required
    category: Literal[
        "HARM_CATEGORY_UNSPECIFIED",
        "HARM_CATEGORY_HATE_SPEECH",
        "HARM_CATEGORY_DANGEROUS_CONTENT",
        "HARM_CATEGORY_HARASSMENT",
        "HARM_CATEGORY_SEXUALLY_EXPLICIT",
        "HARM_CATEGORY_CIVIC_INTEGRITY",
        "HARM_CATEGORY_IMAGE_HATE",
        "HARM_CATEGORY_IMAGE_DANGEROUS_CONTENT",
        "HARM_CATEGORY_IMAGE_HARASSMENT",
        "HARM_CATEGORY_IMAGE_SEXUALLY_EXPLICIT",
        "HARM_CATEGORY_JAILBREAK",
    ]
    # Optional
    method: Literal["HARM_BLOCK_METHOD_UNSPECIFIED", "SEVERITY", "PROBABILITY"]
    # Required
    threshold: Literal[
        "HARM_BLOCK_THRESHOLD_UNSPECIFIED",
        "BLOCK_LOW_AND_ABOVE",
        "BLOCK_MEDIUM_AND_ABOVE",
        "BLOCK_ONLY_HIGH",
        "BLOCK_NONE",
        "OFF",
    ]


class GenerateContentRequest(TypedDict, total=False):
    """Request message for [PredictionService.GenerateContent]."""

    # Optional
    cachedContent: str
    # Required
    contents: list[Content]
    # Optional
    generationConfig: GenerationConfig
    # Optional
    labels: dict[str, str]
    # Optional
    modelArmorConfig: dict[str, Any]
    # Optional
    safetySettings: list[SafetySetting]
    # Optional
    systemInstruction: Content
    # Optional
    toolConfig: ToolConfig
    # Optional
    tools: list[Tool]


class Candidate(TypedDict, total=False):
    """A response candidate generated from the model."""

    # Output only
    avgLogprobs: float
    # Output only
    citationMetadata: dict[str, Any]
    # Output only
    content: Content
    # Output only
    finishMessage: str
    # Output only
    finishReason: Literal[
        "FINISH_REASON_UNSPECIFIED",
        "STOP",
        "MAX_TOKENS",
        "SAFETY",
        "RECITATION",
        "OTHER",
        "BLOCKLIST",
        "PROHIBITED_CONTENT",
        "SPII",
        "MALFORMED_FUNCTION_CALL",
        "MODEL_ARMOR",
        "IMAGE_SAFETY",
        "IMAGE_PROHIBITED_CONTENT",
        "IMAGE_RECITATION",
        "IMAGE_OTHER",
        "UNEXPECTED_TOOL_CALL",
        "NO_IMAGE",
    ]
    # Output only
    groundingMetadata: dict[str, Any]
    # Output only
    index: int
    # Output only
    logprobsResult: dict[str, Any]
    # Output only
    safetyRatings: list[dict[str, Any]]
    # Output only
    urlContextMetadata: dict[str, Any]


class UsageMetadata(TypedDict, total=False):
    """Usage metadata about the content generation request and response. This message provides a
    detailed breakdown of token usage and other relevant metrics."""

    # Output only
    cacheTokensDetails: list[dict[str, Any]]
    # Output only
    cachedContentTokenCount: int
    # The total number of tokens in the generated candidates
    candidatesTokenCount: int
    # Output only
    candidatesTokensDetails: list[dict[str, Any]]
    # The total number of tokens in the prompt
    promptTokenCount: int
    # Output only
    promptTokensDetails: list[dict[str, Any]]
    # Output only
    thoughtsTokenCount: int
    # Output only
    toolUsePromptTokenCount: int
    # Output only
    toolUsePromptTokensDetails: list[dict[str, Any]]
    # The total number of tokens for the entire request
    totalTokenCount: int
    # Output only
    trafficType: Literal[
        "TRAFFIC_TYPE_UNSPECIFIED",
        "ON_DEMAND",
        "ON_DEMAND_PRIORITY",
        "ON_DEMAND_FLEX",
        "PROVISIONED_THROUGHPUT",
    ]


class PromptFeedback(TypedDict, total=False):
    """Content filter results for a prompt sent in the request. Note: This is sent only in the first
    stream chunk and only if no candidates were generated due to content violations."""

    # Output only
    blockReason: Literal[
        "BLOCKED_REASON_UNSPECIFIED",
        "SAFETY",
        "OTHER",
        "BLOCKLIST",
        "PROHIBITED_CONTENT",
        "MODEL_ARMOR",
        "IMAGE_SAFETY",
        "JAILBREAK",
    ]
    # Output only
    blockReasonMessage: str
    # Output only
    safetyRatings: list[dict[str, Any]]


class GenerateContentResponse(TypedDict, total=False):
    """Response message for [PredictionService.GenerateContent]."""

    # Output only
    candidates: list[Candidate]
    # Output only
    createTime: str
    # Output only
    modelVersion: str
    # Output only
    promptFeedback: PromptFeedback
    # Output only
    responseId: str
    # Usage metadata about the response(s)
    usageMetadata: UsageMetadata
